### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by csr** [didierbrun/DBPathRecognizer#15]
Hey there,

Thanks for the amazing library. I have used it in one of my apps. – Do you have a list of the "combinations" for the numbers from 0 to 9?

Cheers,
Cesare

**Comment by didierbrun** [comment]
Hello Cesare,

Sorry for the late response, I'd try something like : 
0 -> 432107654
1 -> 2 & 72
2 -> 701230
3 -> 0123401234
4 -> 202 & 302
5 -> 4201234
6 -> 32107654
7 -> 03
8 -> 5670123210765
9 -> 456701234

I think you should also use a customFilter for the 1 versus 7, and the 0 versus 6.

Hope it helps.

**Comment by csr** [comment]
Thanks, that's very helpful! Closing this for now.
