### ISSUE TITLE
It is possible to do this same with digits for 0 to 9 ?

### ISSUE THREAD

**Issue by MiteshiOS** [didierbrun/DBPathRecognizer#16]
I want getsture recognizer for digit. Please let me if this is possible within your current structure.

**Comment by didierbrun** [comment]
Sure, You have to add the desired models, and that's all.

For example : recognizer.addModel(PathModel(directions: [7, 2], datas:"1"))

**Comment by MiteshiOS** [comment]
@didierbrun Thank you for the reply. But i have one confusion over here.
I did it for digit 3 
recognizer.addModel(PathModel(directions: [0,1,2,3,4,1,2,3,4], datas:"3" as AnyObject))

It is working fine if i write proper digit 3 but it is also recognising some patterns which are not related to 3. Please take a look on screenshot.
![screen shot 2018-08-11 at 7 49 23 pm](https://user-images.githubusercontent.com/17427703/43992712-f56076fc-9d9f-11e8-9e25-98c83124bfc4.png)
Let me know if there is any way to handle it.

**Comment by didierbrun** [comment]
You should use a custom filter to discriminate this kind of false-positive. 

For exemple :
- count the number of direction change on the x axis (should be 3 for the 3)
- apply a more strict score threshold to validât this path
