### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [didierbrun/DBPathRecognizer#8]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by ugomarinelli** [comment]
Hi lfarah, 

If you want I converted it in swift 3
https://github.com/ugomarinelli/DBPathRecognizer

I am still waiting for didier to accept my pull request :).

**Comment by santanu4ver** [comment]
@ugomarinelli I'm still having convert to latest Swift syntax dialog when opened the project in XCode. Even upon accepting them, the project continues to error:

`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

Do you suggest anything else I need to do to make it work?

**Comment by ugomarinelli** [comment]
@santanu4ver in the "Build Settings" of your project's target , search for "Use Legacy Swift Language Version" and set it to "No".

After that it wont ask you to convert it ! 
This is a reccurent issue for many framework that are not recognized as Swift 3. 

Tell me if you have any issues !

**Comment by santanu4ver** [comment]
@ugomarinelli Thanks for the help! That works! It's running clean and nice 👍

**Comment by didierbrun** [comment]
Hello guys, 

ugomarinelli, thanks for Swift 3 support :)
