### ISSUE TITLE
Can support Chinese characters?

### ISSUE THREAD

**Issue by ahkkud** [didierbrun/DBPathRecognizer#9]
Can support Chinese characters?

**Comment by didierbrun** [comment]
Hello zhangyangsk8, 

Right now, DBPathRecognizer only support one stroke at the same time. I imagine that you need several strokes sequence to identify one chinese character. But's it's not impossible, maybee use DBPathRecognizer in a wrapper that hold several strokes and add all the costs (via custom filters).
